### ISSUE TITLE
Use with hardware MIDI device?

### ISSUE THREAD

**Issue by Xaeroxe** [spaztron64/th98tuc_site#13]
Hi, I just got an SC-55. I've been able to use it successfully for other Dosbox X games out of the box however the Dosbox X bundled with this seems to be using an emulated MIDI device. What can I change in the config files to have it use my MIDI device instead?

**Comment by Xaeroxe** [comment]
So I'm realizing this game probably can't make use of an SC-55, so I'm closing this.

**Comment by nmlgc** [comment]
TH02 has a separate MIDI soundtrack, so this issue might still be in relevant for that game?

**Comment by Xaeroxe** [comment]
When the game is properly configured TH02 plays MIDI correctly. So there isn't a problem for me.
