### ISSUE TITLE
`LICENSE` is misleading

### ISSUE THREAD

**Issue by Jayman2000** [spaztron64/th98tuc_site#3]
Normally, a top-level `LICENSE` file denotes the license for an entire project. This project contains  files from many different sources, most of which aren’t available under [the MIT license](https://github.com/spaztron64/th98tuc_site/blob/main/LICENSE). For example,
- [DOSBox-X is under GPLv2](https://github.com/joncampbell123/dosbox-x/blob/master/COPYING)
- I’m not sure what license Neko Project Ⅱ is under, but it’s certainly not [“Copyright (c) 2021 spaztron64”](https://github.com/spaztron64/th98tuc_site/blob/4e1569c61868b342447aa3698ebcbab789c83e72/LICENSE#L3).
- I’m assuming that the Touhou games themselves are unlicensed.

For project like this one, I would recommend using [REUSE](https://reuse.software/). REUSE provides a standardized way to declare the license of each file in a project. For unlicensed files, I guess we could have a NoLicense [LicenseRef](https://reuse.software/faq/#custom-license).

**Comment by spaztron64** [comment]
Whoops, force of habit. I intended to just license the website itself, totally forgetting that the license also covers the packages themselves since they're distributed under the same repo, which of course contain software I have no rights over. I'll see what I can do, thanks for the suggestion.

**Comment by spaztron64** [comment]
For now I'll just remove the top level license file, and move it's contents to only be in my own HTML.
